seven.hex: seven.ihx
	packihx seven.ihx > seven.hex

seven.ihx: seven.c
	sdcc seven.c


#Windows 10 (Powershell) using "erase" instead of "rm"
clean:
	erase *.ihx *.lk *.lst *.mem *.rel *.rst *.sym *.map *.asm *.bin